# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from .models import GCC_resnet18_cifar,GCC_resnet18_stl,propos_resnet18_cifar2,propos_resnet18_cifar1,propos_resnet18_stl,propos_resnet18_stl_for_size64,propos_resnet34_cifar,propos_resnet34_stl,propos_oriresnet18,propos_resnet50_imagent,SeCu_resnet18_cifar,SeCu_resnet50_imagent