algorithm: clusmatch
save_dir: ClusMatch+ProPos/cifar20
save_name: clusmatch_cifar10_600_0_propos
overwrite: True


load_path: pretrain/ProPos/ProPos+CIFAR-100+ResNet-18
label_idx_name: cifar20_propos_idx_6000.npy
label_target_name: cifar20_propos_target_6000.npy



resume: False




use_tensorboard: True
use_ema_for_train: False
use_wandb: False

cluster_weight: 0.5
ulb_loss_ratio: 0.5

neg_loss_ratio: 0.5
slow_lr: 0.0002
fast_lr: 0.02

cluster_warm_up_iter: 8192

epoch: 128
num_train_iter: 65536
num_eval_iter: 1024
num_log_iter: 256
num_labels: 6000
batch_size: 64
eval_batch_size: 256
num_train_lb_update_iter: 512
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001
# ent_loss_ratio: 0.0


uratio: 7
use_quantile: False
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net: propos_resnet18_cifar2
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 20
num_workers: 9
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: false
dist_url: tcp://127.0.0.1:10068
dist_backend: nccl
gpu: None
