algorithm: freematch_neg
save_dir: /propos_semi/cifar10
save_name: freematchneg_cifar10_600_0_propos
load_path: /pretrain/cifar10-1000-10-all
overwrite: True
label_idx_name: cifar10_propos_idx_600.npy
label_target_name: cifar10_propos_target_600.npy

# label_idx_name: cifar10_0.01random_idx_600.npy
# label_target_name: cifar10_0.01random_target_600.npy

# label_idx_name: cifar10_overcluster_cifar20-r18-propos_idx_6000.npy
# label_target_name: cifar10_overcluster_cifar20-r18-propos_target_6000.npy

# label_idx_name: cifar10_new_cifar20-r18-propos_idx_600.npy
# label_target_name: cifar10_new_cifar20-r18-propos_target_600.npy
use_tensorboard: True
use_wandb: False

weight_decay: 0.0005
cluster_weight: 0.5
ulb_loss_ratio: 0.5
neg_loss_ratio: 0.5
# slow_lr: 0.01
# fast_lr: 0.01

slow_lr: 0.0002
fast_lr: 0.02

use_mod: False 
epoch: 128
num_train_iter: 65536
num_eval_iter: 1024
num_log_iter: 256
num_labels: 600
batch_size: 64
eval_batch_size: 256
num_train_lb_update_iter: 512
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001

uratio: 7
use_quantile: False
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
momentum: 0.9

layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net: propos_resnet18_cifar2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 9
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: false
dist_url: tcp://127.0.0.1:10068
dist_backend: nccl
gpu: None
